### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by elbamos** [bhpfelix/PyTorch-SRResNet-AC-DRAGAN#1]
Hi, I'm attempting to replicate this paper also.  Have you done anything to try to reproduce the dataset they used? 

(I'm not sure that the model used in the paper would work properly on CelebA, since it needs 128x128 inputs.  I'm assuming you reduced the number of layers to compensate.)

**Comment by bhpfelix** [comment]
Hi, thanks for the comments. I used the aligned and cropped images provided by the CelebA dataset; the authors provided cropped faces readily resized to size 218x178, so I just matched the shorter edge to 128 and used a 128x128 center crop. As for reproducing the dataset, I followed the instructions provided by the authors and collected about 40,000 face images, but I couldn't go through the entire dataset to remove all the false positives and bad images. I am currently not getting satisfying results. I guess it's either due to not enough data or too many bad images.
